### ISSUE TITLE
the analyse python script can not run with this error

### ISSUE THREAD

**Issue by shenhequnying** [bengland2/gluster-profile-analysis#4]
`command:pythonextract-glvolprof.py /var/tmp/gvp-client-2016-08-18-11-06.log

result:
Traceback (most recent call last):
  File "extract-glvolprof.py", line 605, in <module>
    main()
  File "extract-glvolprof.py", line 601, in main
    parse_input(fn)
  File "extract-glvolprof.py", line 226, in parse_input
    start_time = time.mktime(time.strptime(lines[0], '%Y-%m-%d-%H-%M')) * 1000
  File "/usr/lib64/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data 'Thu Aug 18 11:06:54 CST 2016' does not match format '%Y-%m-%d-%H-%M'`

**Comment by bengland2** [comment]
sorry I didn't see this issue before, I don't think I got e-mail on this.  can you post the input file somewhere we can see it, like pastebin?
