### ISSUE TITLE
gvp-client-[Timestamp].log file is not in expected format

### ISSUE THREAD

**Issue by g1patnaik** [bengland2/gluster-profile-analysis#7]
```
# python extract-gl-client-prof.py /var/tmp/gvp-client-2017-10-24-06-52.log
Traceback (most recent call last):
  File "extract-gl-client-prof.py", line 520, in <module>
    main()
  File "extract-gl-client-prof.py", line 516, in main
    parse_input(fn)
  File "extract-gl-client-prof.py", line 236, in parse_input
    expected_sample_count = int(tokens[0])
ValueError: invalid literal for int() with base 10: 'Tue'
```

Am I doing anything wrong here or is it a bug? I have attache the log file for reference, 
[gvp-client-2017-10-24-06-52.log](https://github.com/bengland2/gluster-profile-analysis/files/1409490/gvp-client-2017-10-24-06-52.log)

**Comment by jiriwetter** [comment]
It should be correct - doc says:

> By default, the output file is called gvp-client-[Timestamp].log and saved in /var/tmp/. Then run the extract script on that output file:
> 
> python extract-gl-client-prof.py /var/tmp/gvp-client-[Timestamp].log
> 
> The output (a bunch of CSV files and an HTML summary page) is placed in a subdirectory in /var/tmp named similar to the supplied log file.

I got same `ValueError` exception.

**Comment by ce107** [comment]
The solution is for the first line to contain the sample count and the sample duration  (two numbers in one line). Still the monitoring script needs to be modified to do that. Any hope this might be looked into?
